# Generated by Django 2.2.6 on 2019-11-15 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(choices=[('AB', 'AB'), ('BC', 'BC')], max_length=100),
        ),
    ]
